{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4f2b812c",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "# Import necessary libraries\n",
    "import pandas as pd\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.metrics import mean_squared_error, r2_score\n",
    "import joblib\n",
    "\n",
    "# Create dataset\n",
    "\n",
    "road_data = {\n",
    "    'speed_limit': [50, 70, 90, 100, 110, 60, 80],\n",
    "    'light_conditions': [1, 2, 3, 1, 2, 3, 2],\n",
    "    'weather_conditions': [1, 3, 2, 1, 2, 3, 1],\n",
    "    'road_surface': [1, 2, 3, 1, 2, 3, 2],\n",
    "    'vehicle_age': [2, 5, 1, 3, 6, 4, 2],\n",
    "    'driver_experience': [10, 4, 15, 7, 3, 5, 9],\n",
    "    'num_vehicles_involved': [1, 2, 2, 3, 1, 2, 3],\n",
    "    'accident_severity': [1, 2, 3, 2, 3, 2, 1]\n",
    "}\n",
    "\n",
    "df = pd.DataFrame(road_data)\n",
    "df.to_csv('road_accidents.csv', index=False)\n",
    "print(\"Road accident dataset 'road_accidents.csv' generated successfully!\\n\")\n",
    "\n",
    "\n",
    "# Prepare data\n",
    "\n",
    "X = df[['speed_limit', 'light_conditions', 'weather_conditions', 'road_surface',\n",
    "        'vehicle_age', 'driver_experience', 'num_vehicles_involved']]\n",
    "y = df['accident_severity']\n",
    "\n",
    "# Split dataset into training and test portions\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)\n",
    "\n",
    "\n",
    "# linear regression model\n",
    "\n",
    "model = LinearRegression()\n",
    "model.fit(X_train, y_train)\n",
    "\n",
    "# Save the trained model for future use\n",
    "joblib.dump(model, 'road_accident_model.pkl')\n",
    "\n",
    "# Evaluate model performance\n",
    "\n",
    "y_pred = model.predict(X_test)\n",
    "mse = mean_squared_error(y_test, y_pred)\n",
    "r2 = r2_score(y_test, y_pred)\n",
    "\n",
    "print(\"Model Performance Summary:\")\n",
    "print(f\"Mean Squared Error (MSE): {mse:.2f}\")\n",
    "print(f\"Coefficient of Determination (R²): {r2:.2f}\\n\")\n",
    "\n",
    "#Test model with new scenario\n",
    "\n",
    "sample_input = pd.DataFrame({\n",
    "    'speed_limit': [85],\n",
    "    'light_conditions': [2],\n",
    "    'weather_conditions': [1],\n",
    "    'road_surface': [2],\n",
    "    'vehicle_age': [3],\n",
    "    'driver_experience': [6],\n",
    "    'num_vehicles_involved': [2]\n",
    "})\n",
    "\n",
    "predicted_value = model.predict(sample_input)[0]\n",
    "print(f\"Estimated Accident Severity Level: {predicted_value:.2f}\")\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
